### ISSUE TITLE
can not download video

### ISSUE THREAD

**Issue by mehmetsefabalik** [sub2u/vimeo-downloader#9]
Hey, I am trying to download videos from vimeo, but It gives me this error: 
`  

    events.js:167
    throw er; // Unhandled 'error' event
    ^

    Error: Status code 503
    at ClientRequest.<anonymous> (/Users/../../node_modules/vimeo-downloader/lib/index.js:110:28)
    at ClientRequest.emit (events.js:182:13)
    at ClientRequest.EventEmitter.emit (domain.js:442:20)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:555:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:109:17)
    at TLSSocket.socketOnData (_http_client.js:441:20)
    at TLSSocket.emit (events.js:182:13)
    at TLSSocket.EventEmitter.emit (domain.js:442:20)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at TLSSocket.Readable.push (_stream_readable.js:219:10)
    at TLSWrap.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
    Emitted 'error' event at:
    at ClientRequest.<anonymous> (/Users/.../node_modules/vimeo-downloader/lib/index.js:110:14)
    at ClientRequest.emit (events.js:182:13)
    [... lines matching original stack trace ...]
    at TLSWrap.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)`

my code: 
`
const ytdl = require('ytdl-core');
const  UploadStream = require('s3-stream-upload');`
`const  S3 = require('aws-sdk').S3;`
`let s3 = new S3();`
`vidl('https://vimeo.com/281424879')`
`.pipe(UploadStream(s3, { Bucket: 'name', Key: 'key' }))`
`.on('error', function(err) {
                        console.log('error while downloading', err)
                    })`
`.on('finish', function() {
                        console.log('finished downloading')
                    });`

Anyone have an idea?

**Comment by sub2u** [comment]
@mehmetsefabalik Seems like youtube API giving 503 status.
There may be multiple reasons for it https://www.imobie.com/support/how-to-fix-youtube-error-503.htm
